name: Build LaTeX PDF
on:
  push:
    branches:
      - main
      - auto-build-pdf
jobs:
  build_correctness_deciders:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile correctness-deciders.pdf
        uses: xu-cheng/latex-action@v3
        with:
          root_file: deciders/correctness-deciders.tex
          work_in_root_file_dir: true
      - name: Create branch with PDF file
        uses: EndBug/add-and-commit@v9
        with:
          add: '-f deciders/correctness-deciders.pdf'
          default_author: github_actions
          new_branch: build-latex-pdf
          push: 'origin build-latex-pdf --set-upstream --force'
